version: '3.9'
services:
  db:
    image: mysql:8.0.29
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Manaus
      MYSQL_ROOT_PASSWORD: lancamento123
      MYSQL_USER: lancamento
      MYSQL_PASSWORD: lancamento123
      MYSQL_DATABASE: lancamento
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - joao-network
  reserva-api:
    image: jlfilho/lancamento-api
    restart: always
    build: ./
    working_dir: /lancamento-api-v3
    environment:
      TZ: America/Manaus
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/lancamento?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: lancamento
      SPRING.DATASOURCE.PASSWORD: lancamento123
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - joao-network
networks:
  joao-network:
    driver: bridge