CREATE TABLE `permissao` (
  `codigo` bigint NOT NULL AUTO_INCREMENT,
  `descricao` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`codigo`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `permissao` VALUES (1,'ROLE_CADASTRAR_CATEGORIA'),(2,'ROLE_PESQUISAR_CATEGORIA'),(3,'ROLE_ATUALIZAR_CATEGORIA'),(4,'ROLE_REMOVER_CATEGORIA'),(5,'ROLE_CADASTRAR_PESSOA'),(6,'ROLE_PESQUISAR_PESSOA'),(7,'ROLE_ATUALIZAR_PESSOA'),(8,'ROLE_REMOVER_PESSOA'),(9,'ROLE_CADASTRAR_LANCAMENTO'),(10,'ROLE_PESQUISAR_LANCAMENTO'),(11,'ROLE_ATUALIZAR_LANCAMENTO'),(12,'ROLE_REMOVER_LANCAMENTO'),(13,'ROLE_CADASTRAR_USUARIO'),(14,'ROLE_PESQUISAR_USUARIO'),(15,'ROLE_ATUALIZAR_USUARIO'),(16,'ROLE_REMOVER_USUARIO'),(17,'ROLE_CADASTRAR_PERMISSAO'),(18,'ROLE_PESQUISAR_PERMISSAO'),(19,'ROLE_ATUALIZAR_PERMISSAO'),(20,'ROLE_REMOVER_PERMISSAO');
